name: minibus
description: A minimal synchronous event bus.
version: 0.0.2
homepage: https://github.com/daftspaniel/minibus
author: Davy Mitchell <daftspaniel@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
